package com.ToniC;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author bernat
 */
public class JControlsPanel extends javax.swing.JPanel implements ActionListener {
    
    HexBoard board;

    /**
     * Creates new form JControlsPanel
     */
    
    public JControlsPanel(HexBoard board) {
        initComponents();
        btnStart.addActionListener(this);
        this.board = board;
    }

    public void setPlayer1Name(String name) {
        if (name.length() > 10) {
            name = name.substring(0, 10) + 1;
        }
        lblPlayer1.setText("Player 1: " + name);
    }

    public void setPlayer2Name(String name) {
        if (name.length() > 10) {
            name = name.substring(0, 10) + 1;
        }
        lblPlayer2.setText("Player 2: " + name);
    }    

    public void setThinking(boolean thinking) {
        //lblThinking..setBusy
        lblThinking.setVisible(thinking);
    }

    public void setPlayer1Message(String msg) {
        txfPlayer1.setText(msg);
    }

    public void setPlayer2Message(String msg) {
        txfPlayer2.setText(msg);
    }    

    public void setButtonText(String txt) {
        btnStart.setText(txt);
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        board.OnStartClicked();
    }    

    public void setButtonEnabled(boolean b) {
        btnStart.setEnabled(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPlayer1 = new javax.swing.JLabel();
        lblPlayer2 = new javax.swing.JLabel();
        txfPlayer1 = new javax.swing.JTextField();
        txfPlayer2 = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();
        lblThinking = new JLabel(new ImageIcon(this.getClass().getResource("/resources/Preloader.gif")));

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(270, 348));
        setMinimumSize(new java.awt.Dimension(270, 348));

        lblPlayer1.setText("jLabel1");

        lblPlayer2.setText("jLabel2");

        txfPlayer1.setEditable(false);
        txfPlayer1.setText("jTextField1");

        txfPlayer2.setEditable(false);
        txfPlayer2.setText("jTextField2");

        btnStart.setText("Start");
        btnStart.setToolTipText("");

        lblThinking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThinking.setMaximumSize(new java.awt.Dimension(128, 128));
        lblThinking.setMinimumSize(new java.awt.Dimension(128, 128));
        lblThinking.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblPlayer2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPlayer1))
                            .addComponent(txfPlayer2)
                            .addComponent(txfPlayer1)
                            .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lblThinking, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPlayer1)
                .addGap(18, 18, 18)
                .addComponent(txfPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblPlayer2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblThinking, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnStart)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel lblPlayer1;
    private javax.swing.JLabel lblPlayer2;
    private javax.swing.JLabel lblThinking;
    private javax.swing.JTextField txfPlayer1;
    private javax.swing.JTextField txfPlayer2;
    // End of variables declaration//GEN-END:variables

}
